<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:test" xmlns:t="urn:test" elementFormDefault="qualified">
  <xs:complexType name="BaseRequestType">
    <xs:sequence>
      <xs:element name="header" type="xs:string"/>
      <xs:element name="user" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="AuthRequest">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="t:BaseRequestType">
          <xs:sequence>
            <xs:element name="token" type="xs:string"/>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
</xs:schema>
